# Generated by Django 5.2.6 on 2025-11-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "spotify_artist_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Artists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VocalStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Vocal Styles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_album_id",
                    models.CharField(
                        db_index=True,
                        help_text="Spotify's unique album identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "cover_art_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("spotify_url", models.URLField(max_length=500)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_set",
                        to="catalog.artist",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="album_set",
                        to="catalog.genre",
                    ),
                ),
                (
                    "vocal_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="album_set",
                        to="catalog.vocalstyle",
                    ),
                ),
            ],
            options={
                "ordering": ["-release_date", "-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["spotify_album_id"],
                        name="catalog_alb_spotify_80199d_idx",
                    ),
                    models.Index(
                        fields=["-release_date"], name="catalog_alb_release_048cce_idx"
                    ),
                    models.Index(
                        fields=["artist", "genre", "vocal_style"],
                        name="catalog_alb_artist__27fa83_idx",
                    ),
                ],
            },
        ),
    ]
