# Generated by Django 5.2.6 on 2025-11-01 08:29

from django.db import migrations
from django.utils.text import slugify


def seed_genres_and_vocal_styles(apps, schema_editor):
    """Seed Genre and VocalStyle tables with initial progressive metal data."""
    Genre = apps.get_model("catalog", "Genre")
    VocalStyle = apps.get_model("catalog", "VocalStyle")

    # Seed Genres
    genres = [
        "Progressive Metal",
        "Technical Death Metal",
        "Djent",
        "Post-Metal",
        "Atmospheric Progressive Metal",
        "Progressive Death Metal",
        "Progressive Metalcore",
        "Instrumental Progressive Metal",
    ]

    for genre_name in genres:
        Genre.objects.get_or_create(
            name=genre_name, defaults={"slug": slugify(genre_name)}
        )

    # Seed Vocal Styles
    vocal_styles = [
        "Clean Vocals",
        "Harsh Vocals",
        "Mixed Vocals (Clean & Harsh)",
        "Instrumental (No Vocals)",
    ]

    for vocal_name in vocal_styles:
        VocalStyle.objects.get_or_create(
            name=vocal_name, defaults={"slug": slugify(vocal_name)}
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded data if migration is reversed."""
    Genre = apps.get_model("catalog", "Genre")
    VocalStyle = apps.get_model("catalog", "VocalStyle")

    Genre.objects.all().delete()
    VocalStyle.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_genres_and_vocal_styles, reverse_seed),
    ]
