# Generated by Django 5.2.6 on 2025-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_seed_genres_vocal_styles"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this synchronization completed",
                    ),
                ),
                (
                    "albums_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of new albums added during this sync",
                    ),
                ),
                (
                    "albums_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of existing albums updated during this sync",
                    ),
                ),
                (
                    "albums_skipped",
                    models.IntegerField(
                        default=0,
                        help_text="Number of albums skipped (already current)",
                    ),
                ),
                (
                    "total_albums_in_catalog",
                    models.IntegerField(
                        help_text="Total album count in catalog after this sync"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether sync completed successfully"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if sync failed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Record",
                "verbose_name_plural": "Sync Records",
                "ordering": ["-sync_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-sync_timestamp"], name="idx_sync_timestamp_desc"
                    )
                ],
            },
        ),
    ]
