# Generated by Django 5.2.6 on 2025-11-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_syncrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current operation state', max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('fetching', 'Fetching'), ('processing', 'Processing'), ('finalizing', 'Finalizing')], help_text='Current sync stage', max_length=50)),
                ('stage_message', models.CharField(blank=True, help_text='Human-readable status text', max_length=200)),
                ('albums_processed', models.IntegerField(default=0, help_text='Number of albums processed so far')),
                ('total_albums', models.IntegerField(blank=True, help_text='Total albums to process', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When sync operation began')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sync operation finished', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address that triggered sync', null=True)),
            ],
            options={
                'verbose_name': 'Sync Operation',
                'verbose_name_plural': 'Sync Operations',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='idx_sync_op_status'), models.Index(fields=['-started_at'], name='idx_sync_op_started')],
            },
        ),
    ]
