# Generated by Django 5.2.6 on 2025-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_syncoperation_current_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_cover_cached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when cover art was cached', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_cover_url',
            field=models.URLField(blank=True, db_index=True, help_text='Cached Spotify cover art URL fetched on-demand', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_metadata_cached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when metadata was cached', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_metadata_json',
            field=models.JSONField(blank=True, help_text='Cached detailed Spotify metadata (genres, tracks, popularity)', null=True),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current operation state', max_length=20),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['spotify_cover_cached_at'], name='catalog_alb_spotify_709a16_idx'),
        ),
    ]
