# Generated by Django 5.2.6 on 2025-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_spotify_cache_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='album',
            name='catalog_alb_artist__27fa83_idx',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Genres this album belongs to (supports multiple genres)', related_name='albums', to='catalog.genre'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'vocal_style'], name='catalog_alb_artist__86c0cc_idx'),
        ),
    ]
