# Generated by Django 5.2.6 on 2025-11-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_change_album_genre_to_many_to_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_user_id', models.CharField(db_index=True, help_text="Spotify's unique user ID", max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, help_text='URL to Spotify profile picture', max_length=500, null=True)),
                ('is_admin', models.BooleanField(db_index=True, default=False, help_text='Administrator flag for application access control')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_token', to='catalog.user')),
            ],
            options={
                'db_table': 'catalog_spotify_token',
            },
        ),
    ]
