# Generated by Django 5.2.6 on 2025-11-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_user_spotifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='canonical_genre',
            field=models.ForeignKey(blank=True, help_text='If this is a duplicate/alias, select the canonical genre to use instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_ignored',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide this genre from filters and UI'),
        ),
    ]
