# Generated by Django 5.2.6 on 2025-12-30 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_genre_management_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_by_users', to='catalog.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_albums', to='catalog.user')),
            ],
            options={
                'verbose_name': 'Listened Album',
                'verbose_name_plural': 'Listened Albums',
                'db_table': 'catalog_listened_album',
                'indexes': [models.Index(fields=['user', 'album'], name='idx_user_album'), models.Index(fields=['-listened_at'], name='idx_listened_at_desc')],
                'unique_together': {('user', 'album')},
            },
        ),
    ]
