# Generated by Django 5.2.6 on 2025-12-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_listenedalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_by_users', to='catalog.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_albums', to='catalog.user')),
            ],
            options={
                'verbose_name': 'Ignored Album',
                'verbose_name_plural': 'Ignored Albums',
                'db_table': 'catalog_ignored_album',
                'indexes': [models.Index(fields=['user', 'album'], name='idx_user_album_ignored'), models.Index(fields=['-ignored_at'], name='idx_ignored_at_desc')],
                'unique_together': {('user', 'album')},
            },
        ),
    ]
